final changes for creating and deleting pair users w/ burnettk

diff --git a/bin/create_wemux_user b/bin/create_wemux_user
--- a/bin/create_wemux_user
+++ b/bin/create_wemux_user
@@ -36,49 +36,47 @@ function create_pair_user() {
 
 }
 
-for pair_user in ${user_array} ; do
-  if [[ "$pair_user" != "$(whoami)" ]]; then
-    if is_mac; then
-      pair_user_dir="/Users/${pair_user}"
-    else
-      pair_user_dir="/home/${pair_user}"
-    fi
-    create_pair_user "$pair_user" "$pair_user_dir"
-
-    echo "adding user to authorized keys: ${pair_user}"
-    ssh_public_keys=""
-    if command -v get_ssh_public_key_from_username >/dev/null ; then
-      ssh_public_keys=$(get_ssh_public_key_from_username "$pair_user")
-    fi
-
-    if [[ -z "$ssh_public_keys" ]]; then
-      ssh_public_keys="$(curl --fail "https://github.com/${pair_user}.keys")"
-    fi
-    if [[ -z "$ssh_public_keys" ]]; then
-      >&2 echo "ERROR: Could not grab ssh public key for '${pair_user}'. Check github username or add get_ssh_public_key_from_username command to your PATH"
-      exit 1
-    fi
-
-    while read -r ssh_public_key; do
-      if [[ -n "$ssh_public_key" ]]; then
-        cleaned_key=$(tr '\r' ' ' <<<"$ssh_public_key" | tr '\n' ' ')
-        if [[ "${RS_FORCE_WEMUX:-}" != "false" ]]; then
-          echo "command=\". ~/.bashrc; /usr/local/bin/wemux pair\" ${cleaned_key}" >> /tmp/superawesomestuffthatisgreat
-        else
-          echo "${cleaned_key}" >> /tmp/superawesomestuffthatisgreat
-        fi
-      else
-        >&2 echo "$(print_color red)WARNING: Could not find ssh key for $pair_user. The user will need to add one at https://stash.trstone.com/plugins/servlet/ssh/account/keys$(print_color)"
-      fi
-    done <<<"${ssh_public_keys}"
-
-    # because the wemux script refers to tmux without the full absolute path and therefore, with a command in authorized_keys, it fails
-    echo "export PATH=\"/usr/local/bin:\$PATH\"" > /tmp/superawesomestuffthatisgreatbashrc
-    sudo mv /tmp/superawesomestuffthatisgreatbashrc "$pair_user_dir/.bashrc"
-    sudo mv /tmp/superawesomestuffthatisgreat "$pair_user_dir/.ssh/authorized_keys"
-    sudo chmod 600 "$pair_user_dir/.ssh/authorized_keys"
-    sudo chown -R "$pair_user" "$pair_user_dir"
-
-    echo "$pair_user" >>/var/tmp/no_term_limits_wemux_ssh_users
+if [[ "$pair_user" != "$(whoami)" ]]; then
+  if is_mac; then
+    pair_user_dir="/Users/${pair_user}"
+  else
+    pair_user_dir="/home/${pair_user}"
   fi
-done
+  create_pair_user "$pair_user" "$pair_user_dir"
+
+  echo "adding user to authorized keys: ${pair_user}"
+  ssh_public_keys=""
+  if command -v get_ssh_public_key_from_username >/dev/null ; then
+    ssh_public_keys=$(get_ssh_public_key_from_username "$pair_user")
+  fi
+
+  if [[ -z "$ssh_public_keys" ]]; then
+    ssh_public_keys="$(curl --fail "https://github.com/${pair_user}.keys")"
+  fi
+  if [[ -z "$ssh_public_keys" ]]; then
+    >&2 echo "ERROR: Could not grab ssh public key for '${pair_user}'. Check github username or add get_ssh_public_key_from_username command to your PATH"
+    exit 1
+  fi
+
+  while read -r ssh_public_key; do
+    if [[ -n "$ssh_public_key" ]]; then
+      cleaned_key=$(tr '\r' ' ' <<<"$ssh_public_key" | tr '\n' ' ')
+      if [[ "${RS_FORCE_WEMUX:-}" != "false" ]]; then
+        echo "command=\". ~/.bashrc; /usr/local/bin/wemux pair\" ${cleaned_key}" >> /tmp/superawesomestuffthatisgreat
+      else
+        echo "${cleaned_key}" >> /tmp/superawesomestuffthatisgreat
+      fi
+    else
+      >&2 echo "$(print_color red)WARNING: Could not find ssh key for $pair_user. The user will need to add one at https://stash.trstone.com/plugins/servlet/ssh/account/keys$(print_color)"
+    fi
+  done <<<"${ssh_public_keys}"
+
+  # because the wemux script refers to tmux without the full absolute path and therefore, with a command in authorized_keys, it fails
+  echo "export PATH=\"/usr/local/bin:\$PATH\"" > /tmp/superawesomestuffthatisgreatbashrc
+  sudo mv /tmp/superawesomestuffthatisgreatbashrc "$pair_user_dir/.bashrc"
+  sudo mv /tmp/superawesomestuffthatisgreat "$pair_user_dir/.ssh/authorized_keys"
+  sudo chmod 600 "$pair_user_dir/.ssh/authorized_keys"
+  sudo chown -R "$pair_user" "$pair_user_dir"
+
+  echo "$pair_user" >>/var/tmp/no_term_limits_wemux_ssh_users
+fi
