use ifconfig.me to get public ip if a 10. address cannot be found w/ burnettk

diff --git a/bin/get_pair_command b/bin/get_pair_command
--- a/bin/get_pair_command
+++ b/bin/get_pair_command
@@ -14,7 +14,15 @@ if [[ -n "${NO_TERM_LIMITS_DEFAULT_HOSTNAME_SUFFIX:-}" ]]; then
   domain="${domain}.${NO_TERM_LIMITS_DEFAULT_HOSTNAME_SUFFIX}"
 fi
 ssh_target="$domain"
-ip_from_ifconfig=$(ifconfig | grep netmask | grep "inet 192" | awk '{print $2}' | head -n 1)
+
+# try to find vpn ip
+ip_from_ifconfig=$( (ifconfig | grep netmask | grep "inet 10\." || echo '') | awk '{print $2}' | head -n 1)
+
+# if that fails, find public ip from ifconfig.me
+if [[ -z "$ip_from_ifconfig" ]]; then
+  ip_from_ifconfig="$(curl --silent --fail https://ifconfig.me)"
+fi
+
 ip_from_domain=$(dig +short "$domain")
 if [[ "$ip_from_ifconfig" != "$ip_from_domain" ]]; then
   ssh_target="$ip_from_ifconfig"
