some updates to poet and allow sending multiple libraries to remove poetry lib w/ burnettk

diff --git a/bin/poet b/bin/poet
--- a/bin/poet
+++ b/bin/poet
@@ -14,17 +14,30 @@ if [[ -z "${1:-}" ]]; then
   >&2 echo "usage: $(basename "$0") [command]"
   exit 1
 fi
+shift
 
 if [[ "$command" == "test" ]]; then
-  poetry run coverage run --parallel -m pytest
+  args="$@"
+  if [[ -z "${2:-}" ]] && grep -qE '^test_' <<<"${1:-}" ; then
+    test_file=$(grep -lR --exclude-dir=__pycache__ "$1" tests/)
+    if [[ -z "$test_file" ]]; then
+      >&2 echo "ERROR: test_name specified, but it could not be found in any file"
+      exit 1
+    fi
+    class_name_arg=""
+    expected_class_name=$(basename "$test_file" .py | perl -pe 's/(^|_)(\w)/\U$2/g')
+    if grep -q "^class \<${expected_class_name}\>" "$test_file"; then
+      class_name_arg="::${expected_class_name}"
+    fi
+    args="-s ${test_file}${class_name_arg}::${1}"
+  fi
+  poetry run coverage run --parallel -m pytest $args
 elif [[ "$command" == "update" ]]; then
-  library="${2:-}"
-
-  if [[ -z "${library}" ]]; then
+  if [[ -z "${1:-}" ]]; then
     >&2 echo "usage: $(basename "$0") [update] [library]"
     exit 1
   fi
 
-  remove_python_poetry_library_from_disk "$library"
-  poetry update "$library"
+  remove_python_poetry_library_from_disk "$@"
+  poetry update "$@"
 fi
diff --git a/bin/remove_python_poetry_library_from_disk b/bin/remove_python_poetry_library_from_disk
--- a/bin/remove_python_poetry_library_from_disk
+++ b/bin/remove_python_poetry_library_from_disk
@@ -9,34 +9,36 @@ set -o errtrace -o errexit -o nounset -o pipefail
 
 # HELP: python: removes the given library from the corresponding poetry location. Useful to force poetry to update a package from git or localhost
 
-library_name="${1:-}"
+libraries="$*"
 if [[ -z "${1:-}" ]]; then
-  >&2 echo "usage: $(basename "$0") [library_name]"
+  >&2 echo "usage: $(basename "$0") [library_name1, library_name2, ...]"
   exit 1
 fi
 
 virtual_env_path_line="$(poetry env info | grep Path:)"
 virtual_env_full_path="$(awk '{print $2}' <<<"$virtual_env_path_line" || echo '')"
 
-if ! grep -qE '\<pypoetry\>' <<<"$virtual_env_full_path" ; then
-  >&2 echo "ERROR: Could not find pypoetry in full path: ${virtual_env_full_path}"
-  exit 1
-fi
+for library_name in $libraries; do
+  if ! grep -qE '\<pypoetry\>' <<<"$virtual_env_full_path" ; then
+    >&2 echo "ERROR: Could not find pypoetry in full path: ${virtual_env_full_path}"
+    exit 1
+  fi
 
-full_path_to_src="${virtual_env_full_path}/src/${library_name}"
-if [[ -d "$full_path_to_src" ]]; then
-  set -x
-  rm -rf "$full_path_to_src"
-  set +x
-fi
+  full_path_to_src="${virtual_env_full_path}/src/${library_name}"
+  if [[ -d "$full_path_to_src" ]]; then
+    set -x
+    rm -rf "$full_path_to_src"
+    set +x
+  fi
 
-list_of_directories=$(find "$virtual_env_full_path" -type d | grep -E "/${library_name}(-[0-9]+.*\.dist-info)?$" || echo '')
-if [[ -n "$list_of_directories" ]]; then
-  while read -r dir; do
-    if [[ -d "$dir" ]] && grep -q "$virtual_env_full_path" <<<"$dir"; then
-      set -x
-      rm -rf "$dir"
-      set +x
-    fi
-  done <<<"$list_of_directories"
-fi
+  list_of_directories=$(find "$virtual_env_full_path" -type d | grep -E "/${library_name}(-[0-9]+.*\.dist-info)?$" || echo '')
+  if [[ -n "$list_of_directories" ]]; then
+    while read -r dir; do
+      if [[ -d "$dir" ]] && grep -q "$virtual_env_full_path" <<<"$dir"; then
+        set -x
+        rm -rf "$dir"
+        set +x
+      fi
+    done <<<"$list_of_directories"
+  fi
+done
